#!/bin/bash
# a7crypt v0.12 last mod 2011/11/25
# Latest version at <http://github.com/ryran/b19scripts>
# Copyright 2011 Ryan Sawhill <ryan@b19.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#-------------------------------------------------------------------------------
# This is a super-simple wrapper for gpg.
# The idea is that you could create a shortcut in your desktop environment to
# run this script (making sure to modify the settings to run it in a terminal).
# Whenever you need to do some quick ascii-armor-encrypting of text, you simply
# click the icon, paste in your text, and you're good to go! Likewise for
# decrypting text. Nothing special.
# Feel free to hit me up if you have any questions or suggestions.
#-------------------------------------------------------------------------------

# Check for positional parameters
if [[ $1 = '--openssl' || $1 = '-o' ]] || ! which gpg &>/dev/null; then
	MAIN(){ OPENSSL; }
elif [ $# -ne 0 ]; then
	echo "Simple encryption/decryption using GPG. Meant to be run interactively w/no args."
	echo "An argument of '--openssl' or '-o' is supported, which will force use of OpenSSL"
	echo "instead of GPG for both encryption & decryption."
	exit 1
else
	MAIN(){ GPG; }
fi

# Set colors
RED='\E[31m' ; BLUE='\E[34m' ; BLACK='\E[0m' ; GREEN='\E[32m'


GPG(){
echo -en "Would you like to [${RED}e${BLACK}]ncrypt or [${RED}d${BLACK}]ecrypt? "
read

if [[ $REPLY = e ]]; then
	echo -e "${BLUE}Steps: enter passphrase, type/paste text, Ctrl-d to encrypt"
	echo -e "Pressing Ctrl-d on an EMPTY line will make distinguishing encrypted text easier${BLACK}\n"
	gpg  -ac --force-mdc
	echo -en "\n${GREEN}DONE! Ctrl-c to exit or Enter to go again${BLACK}"
	read
	MAIN
elif [[ $REPLY = d ]]; then
	echo -e "${BLUE}Steps: paste gpg-encrypted message, enter passphrase, Ctrl-d to decrypt${BLACK}\n"
	gpg -d
	echo -en "\n${GREEN}DONE! Ctrl-c to exit or Enter to go again${BLACK}"
	read
	MAIN
else
	echo "Improper input -- must enter 'e' or 'd'"
	MAIN
fi
}

OPENSSL(){
echo -en "Would you like to [${RED}e${BLACK}]ncrypt or [${RED}d${BLACK}]ecrypt? "
read

if [[ $REPLY = e ]]; then
	echo -e "${BLUE}Steps: enter passphrase, type/paste text, Ctrl-d TWICE to encrypt"
	echo -e "Pressing Ctrl-d on an EMPTY line will make distinguishing encrypted text easier${BLACK}\n"
	openssl aes-256-cbc -a -salt
	echo -en "\n${GREEN}DONE! Ctrl-c to exit or Enter to go again${BLACK}"
	read
	MAIN
elif [[ $REPLY = d ]]; then
	echo -e "${BLUE}Steps: enter passphrase, paste openssl-encrypted message, Ctrl-d TWICE to decrypt${BLACK}\n"
	openssl aes-256-cbc -d -a
	echo -en "\n${GREEN}DONE! Ctrl-c to exit or Enter to go again${BLACK}"
	read
	MAIN
else
	echo "Improper input -- must enter 'e' or 'd'"
	MAIN
fi
}

MAIN
