#!/bin/bash
# bb v0.5 last mod 2014/03/19
# Latest version at <http://bit.ly/breakboot>
# Copyright 2012,2013,2014 Ryan Sawhill Aroha <rsaw@redhat.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#
# In fact, this program's sole purpose is to cause boot problems on a RHEL 6
# system, in order to give you practice at fixing such problems.
# Use at your own risk and preferably on a virtual machine.
#-------------------------------------------------------------------------------

# Colors
reset='\033[0;0m'
bold='\033[1;1m'
red='\033[1;31m'

# Location of breakboot configs
cfgfile=/root/.breakboot
fixfile=/root/.breakboot_fix

for i in /etc/sysconfig/{authconfig,network,sshd}; do . $i 2>/dev/null; done
RR=$(awk {print\$2\$4\$3\$1} /etc/[rza]*[-mpq]re*)
L=$(lsb_release -sr)
p=$(cat /tmp/.bbpass 2>/dev/null)
[[ -z $p ]] && p="${L:0:1}$RR$USENIS$NETWORKING$AUTOCREATE_SERVER_KEYS"
functions=$(mktemp -p /dev/shm) && trap "rm $functions 2>/dev/null" EXIT
openssl aes-128-cbc -md sha256 -k "$p" -a -d <<\EOF | zcat >$functions
U2FsdGVkX19ZIP5XDVxthbYQyDYJiO1gfpQnq16wMtnmIK05ZRLNgaZpGDJ1USI5
HdJQo1oG5EbmVOuCXAmGHNPrSaXyZR01LGkVCVnexkNPzASNu6nLJao5YFjEJAit
QEgfnSR5c5cZj8RLv3reNWOJSpQefzES//kMyT/ZRoGjvzkGd6RRb3B6+5b9HplK
J0NflMPczCw30T29SJw9qHjg0rqb5oHFxGoS7rkPGPdM6hHFPIH918JPxBXiwdIz
pQd1exWUYScK+2X4kyDyJMAbWi+c3saHqWIkVev448RpAMY8huqXfU5cN7QnKd/q
mv07+KToFJsZ2OAJKb7k8tDw7CAYXIS5c4Z+5KlW/uy3p4uMqoiXZinieUE2Nua6
9pynIQkxr3Z/c1Sspv0H1PhJUtQLEau8VTQwsVMqdv67+T8VI5dHwux4n6zqAVGB
JfxE1zr7Ty9XaVyNqhwzxXooSitEZOQ3EAiAXHJrlbyjCh+CnjvqcdThiGUa4ZyY
49EcUy2KL7rjS5DXddbVdJOV0LAhIm7BR3ac38SH+ipxjMgsQO1ujO0hvYG7KJgc
IR1Nz9pJa2gpphr/5sNMbHvyIXXSjq6DYWJS5SPblk/7eZqf6wJQXQZEwwfzc+L4
qWYe87Cf5LKwn2DWSd+lznrmlAWdgRF/slozC9y8byW2RzuDB+G6RtXzlamcRs3U
4FinQQaWX7IKlkRV7ShdxxvuiKebOKV0/pLISiI32mrxLhY2we36jRFvHc5jLBl4
if0w/EhnvFwh4aa7P6vg9ZWjqmIYLhRbIKtqckYhJ26hs430plmGa8KQA8Ylq+k1
++oOmjf5U7bKuamScNVsyCVpzDk98l7j2bCKtlYd+4KDaAqRMpRL2cXlgKayitam
71xmSExwu8Nc7D5hGOPOrOAi1jl0AGKEo9M1fZeq270Xqxny+9niahKY+3PSjRWh
shllMR0v4FDSiwHEze0piKjw1Vl19IZJq+93pB7rPA36kiwme7cCGGByIB/F5M1r
1WAipYKrQMKD0XNvFMGJCBGIaQtqa1i8T3Czbhj/hfzYgusZKbtBQViw37vUsx9w
OX9AvOlvvSy8yGUCPGtEf4J2FLfQwnGI8VV7zSAqDCVhM+rnAz3O2a3FqgbidfLE
T0oAQaDEpeYaDK/QllmJ8npeypei6l5hBu0y1hlf8UX5y0kD3V+2rZHdX0kEZdix
W2PcS12eSg1oV6sJKJq3yTzACjIGve2BCt2MNr8yRC7fntkPHuxYiAfxsJNfOnrn
LaSVX7qyjQkiynZozetzycm8EsoXUWEjlZfHIRqL922iJi2n0eEjvzhP69ir0rX8
VhKr65mFBWyOQbVe4WcMT8pXNBKR7ChIKjDIn2n8RHlyVTZ9zJF0AiaGnWmb59AH
NNas1Nt+Mtdgt80Jq/DdrQ5xf7AboFa2b5rfv2dbeVRBkFArfRiQZrilQ/ir4juf
0fICyJzUv74fTyQYYVY48l2L4Yk+SnuWLg4X+74XHuuP/kodpTO9BVppeTOIO47y
3ECMmzQTfhEAC8efIwaJo4aCT0wgFCGWUKOCVCYGH0jRt7eMRbTmp0J89LFf8ZqZ
R3QyEJuPSTAg3SVmqMSXNK0uyp+M+ULJBpBDXL+i8bBJEW+nsLL+n5hM3sNR0EU4
RUTKXx91qGspvTdh9tKzi2H3zHAhfPQqDyjlxJpOaoIOXdAEHOQi78AU5ESESpsE
eGtuJA7SFgS/D9uYSo9IzJL0GV3lZjYIAhx8efLk3wTXZbszvffUS/gfxmNLRTyz
PdQn6QWGTrBuTIbFScgvcbLhw3rK7bWcjxGNJBU0tYKorsaA4/rHqG/GzpveJBx0
pg3gHsjtbMQp7jSp11q9L30wELojog9Tqt/WxNtqnke1FLkuZnp+RykdrVr5tT2k
1QHYdWk2zO6t9DaSmdkCosQl6J6lNK7syipiRvLkV7gF4Kefnh6/2jnZ/EdbmkFQ
0eatHk8cxAAub+05Xq91umh0PNpR4RFnsksPfIaKZ5JLnGabAYo9cCy7E5qaoxxm
uxvMjxwLtB6sJW88uFml5yOuJwfeAbZjW+8Rs7io1RBH8CdXYZshzeC63iS46Ecu
KSD+JXkfD+o4OrvKs1j9TYJdST0bKWXLzbqAfS6RLe3FEWovhqX0aXYDYE8eJ8er
QNtAIGSQZb7NGkofFPQkQx8K2VQleXkVKCearRbvdwtQM/bcVZTydT/r0OGftGYg
yjhuu0n3b+W3hgJOT5oUT5zcjUgy4hJSAgHwabQWI8smuarEJ/Wem6BtRvFNTCzd
okli+Xa7jsCECBwwcm7YIqTNhLqBgmJgwCQtj5aV9JbHiwzSuDKAvEN/1RS+kWY5
Y/t9XN7cWMLi61bGg7b2efU2AJQiukvwIRws24AVutIl8nzxtES5crZjWORmbfa7
oAzbHbTTXXo9Bd5uGbRckNOn5YNDcd7COCxME1LDsLNwKFA0FussHw9gCNM3Q0pu
j0SJwJ5Rc0KI5eaBiqNvlbgbojaR0MVPMQsgi0SivPXhtCMAWqi5N1Gj+ovfpZEm
Z/ENYHxsy+hAqih/C36+hoQhFfTNQpMcX4liHRqSwJMlkYGq1bb607PgrOvZR6S5
Ujan0yiFtVADtqW8o1pVNYkeSI8Ga/u5Dzb4IfQd0mv+7Z4mJSZVynzpQQ8tx3Zn
FwRFY7Vl7B8zw7F0gE6NUaXWhfC6w6F3IRWFpPCnfMSqw2cImqhT5YGo4Up+Ken2
uPLxYiozaCNgq7d5MjHPGTV+oMTLLNcIAPju538BkUyRYYEPDlSeZbNMbbMFFHLV
Gfhd4z0zv5yNmbr/w+2OgQIAq72/SvrdPrW2/UJ2fUvf1LDb99patKTC4FEmJhGq
vnv84VQTzMnESe2+AxLPEOCMuXCh4ZfQIxzK+XVWLIJofdWIR7/TwAvQlHgguzKv
uuN3DVY767L+Ey3c4AqEb0OQJAqbYSo5wkK7xIywcWKwhOZ3T/3mLP+ROU+xf1fm
f7ienvIARs+RDcrd2Q9YTRuxbj9I8xLTtMHENoR9chJv+PBQVJdlVyXnWaidRGPF
7+hrOmdHWr9daT1z7yw4DSIt7iRs9VVtIQI3mUs8KGcCRY2vW8DhNxlcD5ZBInIG
8MVLeUS5eSRGMSSaVMOTxetqvdUxixx4cx4FuR6ZGBM3B8rx3dBbxhIuAVzBXBdC
EIm412Nl7F4eBlYj6JW+rCJPZIcvY2k/ExC3CCXEAudj5FtYcMtM7Dc20K+ldas6
uJXOcsK+9dA0h+far2RH6WlK1OoqY7ngTzifAIkKJSkot4I/xdLgK91hArMsoCJx
kXUiV9/0kNuJSBbCac6MaMrL38goFWlHyxY/lUfCAHQ8yL6LEwF3E/XJHKrSeEFm
WJHEeYl5zXSVeYfVpsCai8dNfVEvvejak047BYz50va4nuXcG9Ua64Tzht7jWblr
b08z+x3RPx4JGxyQa/EQa1CZELXLbn9YoVVWxp5G0D5o3aR27r+6+yBHeajfT9x5
RPo85KchiVVyjnI49Xs82UN0UScSfI7tDdPF5jMfwmhyyXYk8wVGYjzMcoOKT6ig
Eh7BU/H/VAHaY10IGIxLi4sgFJbvuZgXxwYEzFMhzKuVsWThNri9iSBB3EaKkEEq
5ubhcpPHqTQJZ1jzabcbKJpemCYs4CyOBHwU81Bbn4SnC/EKCIX1WKf/wmAV3Ilu
sRML1lb8CdfJFeNbJyoTFKm00+zedIG50QakAXqxQlYSE7jbzTLYMCAWHfBEVQYZ
QU0nzMWr9eHh5/D5615XTnUAuhiBQSIOJURAfYimjtO8fDuPPKlIiMfxO7QQ24Au
ch2LZhUsiERP4szMcxgCfUY23NZc2ImcqmR4tXOUxOyZgySi+lWwvrqIrQlUSk1N
wR1fBh7xHJsmURnvo3K2vQ/1d5x+RrWTZeT2a/zVCJN9vL2qieGKdxrWEgRVgfvq
GTNP2/awem8N/FjlWmeh9XkxNArq8vVjwCC04ar81d5ahft/ARusTWZ0wn42PD7S
dpr2eExbDfMLCAeLTtkD/mgU7olANlBOgBQMUudOk/ukY2KhmULeiTC2Nh985VX2
OdTbNoTVg7VD7vtKfK3G+rRJ24FJF19MVoDOJ3rk8wb11f/3zYcfEvCHCjGQWzMr
C3mNhDkPsqOOK95ZIrQrmsHSadujlqm/tGmSjzsGln5rpUx5+0PZuS6Gz8TA6jGq
6qRptrhBxLs4KgUnojBcKpJjqSqXCpFYSjhUlZkoby/t7MlJ71cFgoVCB0dww+np
WueHdit7youdbNPQpnes90gQTXVuSXfr80e4DLll0nHogEgyuvOacWc3jz8qIo1+
i4C37ZSO4oVB2lhB3GmCX8cplP/Y9swHNFa/j8BZSt39MdsSojfwMkrU34sWC1zP
B8eSG2GMxVvFVy+WjMO7/6fTG1YY2p6zM6v2Vb2u2V78aAkxtAVshLuN1EkdZvo4
P0TdXjeL9N7sdWomaokPQ9F3QRQYpFKRBvsGDNsDBpFgNvZ/yozyNf/w5kEH/qbE
YjGvFPqIYIcT8Ykt6NmrvNHXZ41tvSwbYxmOlxTrgB46ziB5MzS6yK9WRc0rDdT9
avo0Fsc2lHhyQNP6lvnI+APwFITHKNc3JjpQ0wo0QHPAIwI993cuPfCToZhE4JLG
6JTDrrymPjIbcz08deD8AX7ORfjf8JOewq+6nGr/7gxrO7bmHfsTIyGhH6r/fSTs
K7bSy2y9qx4E3drrlg8fqhiApLU5bjdW7HUHW0Je693+201nbFvp9G7yPttnf47K
jGF58NkjOJvHbjzH2cXuUHD2nl15OHHkx6754v9Ph8ROJZnJfKnoDrvap6ktMaWA
mvuks0DyiBH9YFv2fgLmck4DCZVJq0vWJU4U5IbCEsF3iAwtjv8zf/sqcn/ZVJM9
JAeZ68+bILuH3u1fsi4tIpvyTwliIQeQBO8eXj2e2VT5A/0aNxK6XyPNv1gPD/La
SqeofsQ9QM/xTVpPzojG0jiljU1ckE1XK4zBHQdl5sKg8mTn5eh64X2bUnapmaDp
R92x8QH9S0p/gF9bR3bqTj/o9K2gthP9AejE7T8B4Cpv4fJEbPkCFDvFfsA44wFJ
zODN3cpZv45jVsN2iWhp6T5vEpBBwtzlIn6hFTQHi3u1jBGY6dUw2/n9RwfQIq87
ReNCFOaL5wSDuOQ4HB9RU3oPiUjGvRqhWkuD3LBlGiiGuK2+y1Og8AT8mC8IBVEA
LckQ52GfLwWX0AVrK+x/OCMZQpMSZxAqgz7AQU45Zb4Moc/6or5Q9gYF1IOiWnzA
SoTFTY6REqSaTyx+9TqrDssTCotLaXZNbS9UQhyMoDDwfglSmW9CK56dasbj+snH
S7ewYI5D+c2eT6us8Vx7AVfRj0jENrS9Tb3k6EkBzph9sZgqrXqQC1C8Qagn+qlU
Q3vRXY6yXvaRgLh1nAr6v1EXi8eCmfOc6EeVGe/vr1ntxsLCge9WMLiqV5yRJS6S
oD+8HZxAMpmBjmUd4pb2ON61zbMycd8hx0uKQwT6lT1dxsIwyoRCk6pwG23zAuKB
dGkA+/oNRVjAyckzuxYb2ncsWkudb9LIY4Qux5wcGdGHs22gBEZr9NvSQF7zMMmE
jeYnp+DWI545zRr1WIYHa3yVtLMbAb87VOaSKvlMiSdoZ0wK1EX4QGjvRaet/5xw
l6CUzbbz8tQHm9gDIK0ZwgEE1oXysLh+epiYx64X8l2gmu8252imPqI6n3hTpk+d
y7E4wMWWRhHR2POG7COlUDtFW/7yoETi3nKM7C3n7EP2PlULmmT7JnF2YT9YtQna
6NJS0ZJY8rP8VETqT+uU0OP4Z5Kblyw6BoBQWDAAQTlGTpsjU8J4OsAB+1KWPxcD
cOm1EziOjMsxUU3xzcPy3Cr2U5x54jy9NyZNbOqRw69MaWQjAp8tYAa0qkjSbATs
DLtjxiTHG7tyA2DbBKy8AnFfzFgsM6XPlfpqvTAXcVBO9sbqa485cYZLpdBruv6d
9jnZf24LGPFalS1T/DwWOgq8GSlX6hpxWyLgjl4f1QVVu8TNa7hOrT3lH0pnCrW6
M2iU/5dKZ3fYOILwl3EnUUR3aLGgtQZXq/bUjZBWaBPRlIWqaMzec8oS/lEdeins
R+qCM4+cR12OsVPJTBeTGilRRFxtWPHG8nBWueMMGBQ0kD+HI8xpVUPg8gAxwX42
PyZm8BTp0spjrZF/ZWnfnPhCBLZHInNs/YDcI9ty/+2Gwqy6gzH6DsJwrZO5CsEW
R3ACrQTIYBo7G1Igsk+xWf3yN7NO1AbAgsVZyqrkBKXln83Z/KrWCuhhfFbP4Gtl
ZD9Bf0QwGGRk4BxHg8QlVxQ065+NA8W98M6eMRjruE1L92MHuyJwWNEdae1srkVL
z+uwq2zAzlqijyAhOCEFufIjpMKWvc9Y4Hc0xTtCzfxOfVcVOTbbmVIGhPDpET0/
jztGpSGxu0YDSR0FxwLWzt44QrRHtCARfkSWXqb4JrMg4UKS0qOu73681bj52jTE
oC5aOpTLH8bJjUN13DitTUTRPsUsbZWLIaSJ99Q0AC9cj001ZAD5cWoBlUYkCCqD
rngEIXhG+jaDFnOnWGjwA2KQhSp1ixzkfMou4tBOBuZwZ2P4f7tZFodQyqMSf5Pb
LIwz1DTvoLTXJx6amW/IMZchPg4QRhp/aoCOQH9Ds+MifmacfYUa1UPf6Xf1kMMR
pmpL1DL6KCo0TRLgsByV0vCtvj33q3pXp8/qeg5MXxnfzKAzzbzDxcyFtCN1ZJiu
o0ZzCv6pL7nat6FGbXfjUGeHTnldZ/ymUpw9O4zpy4n/8MOSiKzIT/+qMB/RV8uJ
RLjuTqXSGAnTC8rkUy1HrBYPPLAe6tiDKLfErbZRV3jP/9QL0zefewYDsw6bFkxr
XWWEqhl6TcdgLHrn7qd1nnJY2OqYBtMcxETgrUrlalf2x4L3Dj6IE9VyuPaRZoRT
pCDYp8N5QCAFk+FAsG/l9xTPVylQMNN3rspxqGBzSXBtg6iIll/Rbrs5qtv7EVFC
OkHwmWnRxclk05CnDyfdEya3MiGDES45IdP6xOzFE99I2tLYzP0qkdwYxU7l0hC1
c9nstFaB1T/2K0wBv43CBVgcntW4FVTy9IkjIsk7CE9TeX8wzDl2KG3nDDeZq+eG
SnmANOqefeDgwWBVb64t9GrozoXKJj0GRfglua1a7iCwEWmtD/kUP4bzZAvsvnZh
z5r7pdLa8pt6s0a3oMkxs1tNvcw0YNXnhjMVUkJg9l6Vy5Cn5hzhm6Wb5GW5KpFU
SvCNhKejTCyUGApyhvjRFBMBNKsftp3w4mTIogBqgXUvT0ODKPp4WJDYczc2Dq0k
jHBTKk0v0X1FiJk8UzMP+MnT/dR66F/x3lRHCGCRg58PwiVBLlGCYdC0IuuWfO+7
o9Nga7DABNcFIzlhvbxez6e4baPg23GR9lOgQMKyZ73zL0CHX2iF5UIberwIKKKa
94HUg3qMRyBSnYdFrscIRGG/4W7iKYo6C3UAOlr18X/rg6/A6SAMF1HD/UXLzkKi
GYn0uHShzwtrUUsNTv9gfa//k/QkxgT2/B/yzvFb9YMSpaI93pAFwFby/TfVBb+Y
Mgt8L8sPh5OFN4cseRGjbnkz7tbDmbo80lPhFyja/NndJIWn7c9uEBnuaHHQuchY
oEfqznlNjQELsvPvJrBz7n20WPLPEtcJCD1UmL8VHawBcQuBRGpwljnlDpsDcNP7
ncE/n3kTlGWpW7oMo6yS76J/+9zZEwcou0SMEWNTAVtkLl2rU72ifwzF6fUUTa6m
tFkkY3EPCZSfKuFkaKDe1s1+LBXQG6s3tU0BOEH8/2loQvExQirGC9EL8c25+8kh
huT12n3CAsb4Eil85GIEJ8qq28rKZ69w7Fddc7ZoPUazosDB/lUrgtiiJMk50LmK
3AmfOJkFarNQ7XoTkUl+FeGjhso2ysoSKmkY7BQ4KQ6PvHHX6hrKN3LQNLFPDjVH
YWwzPvPs6Iw9Kj0SJstn74UzKEC4gj1oZdvja7McNGp56Sbu1AGTQL1MK9NViOzK
uyceyziPNPvc8tu9G74+Wo+a0g655wIzhRUcLPMLd/3VYIMJsDG9lhfRJ5CfSBSq
nybbF1TRANB8504Ee9N9tvhTKtG4TXwqiDTUVnebCfBq3mkaW3qFWPj3hRmWYJuI
mFFhOjcLFyasCZupE8RO4fx0e0hgFWX0YG5IIszNGn9L/plMXS2lvJs8VWZ8zfTg
saSTVgqsln3PKBsLXIsakSPogkcMdXSKaxjceYOGxpH6sbfQAk4oYKgfI6hHPT5d
yusfl+ihmoJ9wjzoiHin33tDI1AtsAcQ+sW5Jt0L764At5emizPqP48ZHamltC2/
dWQPzf93U+hIwZL2lpi3AECNAV8JD1hqBbIVnRc3QE5XCNwLKGNDiaj1seDfqy46
G7S5ayejLnpMmtLdWX4fa5VRviNNmAxSpEZ1eHlwk9hLkUfmd3sKw4jAqhUHdeE7
9Re4MJAfmNFPh9W4Otybd3w4bfHQOe23qNbkf3o6I+PoC90eXyppk07dfXpvTdYO
7u8QOOIsI3Gc9GC7HfTBXEXSDmeY7PMMKYS4bc3m+22BNSzh9KnPqbbkJonqv/rf
d4MqYg8lsrBE1L0tOst5782i0pDPGlVF5bz70RrVBRmwD0sS1WDcgyh0ea473IF7
U+vHZuKAtUglRWeedvQNOQNTnBwe/iO54qwB76TjO9ko9fVzSULtWocXFYjycDDE
cScoraSYiCGg1FeG/4Q8/TmoinDHf4b8WOyWWkuc9ygZ4xIjx/rUWMYzl+/JqOAR
RS5f0ZF/LvSINMYP/qT4iAbrJ1e83J1N0lOvErBqgvflh5WOKI926Uup7lWnAepb
OffDN9ro5iwUqVLI+n6Ag6WvYeuTcrTeLCxpfw8sGNWtod5yHpJiqnglBcOp/jjN
8SI+ZUUc+DdWxSHwfvB6ccWzqaxm8GTe2gSDZF0XlT046+mBhp3HPpjEeQLEaFum
Q5RoGgimfKn+nzQGxc0KScvryU2C5iQFXfLIMv4CpSFJnxdmCU54aFzFfS5U6lIE
0N+mZrYBBmT32zBwgWtf1laHA1YBo9H4KHE3kJdNvQpbX6ruCG7oMSRq0Rnow4dh
PnLTR00bt2//4xm9XHa4jAC9dpCV9mAWDMast8r6qUq8ZYNsJjLeFF9CUQJ1+9pr
5GD8yb0mbhAKMh9MZyEdEW2SABBNDPjSzJwaqgVypG/vrTVmiljbDlMDcnTSU98Y
f3BoPEBaoON+zP78iYYCykk2MviwXAGEbrmR8Gk9eTj7PVDVJ8LbXt137Wlfj1Q4
YL5uzZ30ifUQhchpJa9LLrSJDoHVnP3W4SWqvw97mtENHAB91aRYSO/IuY8jYul1
O/8vMvPJ3k4ig0QS83Ewpu1mMysIrIJEMLp2q4tWVFMs3ol+Htf+4rDdbqswEgtb
QfOwBwFHeGbP+N2ZtFVPAsusAFJ2NU8nzlbgey0ndQjqBElgI54zobZkrSbmlEoK
iGFlxQLDWj/R/0k6sNX0vH+z1YhFvnFtYzSP3GZ5+1wdIOJYdXrhFdyPdqnYR9lL
f/KjP+JJle//cC4krEp0DiGUdp0JaINbKlXTKZMcJaEy3t17Ii40MEWZkt5RbU2S
qSULA/vKm5Awg1CUQiYlNKa/HdUnkLnNmjo2a8aTUMMzLaNs4EsgkSVQCtvHr9KT
hFNTnyntKwvaaCT1gPAxhQjkB2iGhHIf6MJRmITsSWCb1zBNFSSbIgp+x5jV0qeU
dABhnfXvNBdjNG4l+gCc3H1QO86kqwbnGIHyJtnAIk68eSYDkYHV8sBGO3UVnO8T
df1OQWNa0+zbj01nm67jzGKlCUGCw03wYf1uV3QTqQ00qiMl12GB6CZ1V6KqWPTQ
ZRorvyIWwAudM+afwwAywZVvAqKPdZYhA3cn+JKUqQ4hfax0Ag3ZeYKIaYsDkbgs
eVihmqm52FXZJ8WVjIsjZOidXZInZsedvU66uW4k3qXUaLXIGepWPp5SyGYk8m9q
jw7XbgGM9sRU7K9MOYeROUFULC397Rd1HAs7LXXTBv2zAkwhMNytqIb5EsCw9wgp
E0UAPSuN7tHZ/wHTQc0sGMsGKFGxJaxEzBXpbYE2xZ80ofxnFMGwTGFr8LKAzihF
qpcSi0Ecoq/mFbcWYARPBCh2R5t3kcLZM5uL9jxNJVa5GNJQlkkcHrmRX63vOmtl
EOF

. $functions

USAGE() {
  printf "${bold}Usage: ${0##*/} { 1-10 | next | skip | lesson [1-10|all] | fix }${reset}
  • ${bold}1${reset} thru ${bold}10${reset} to setup a specific exercise
  • ${bold}next${reset} to setup the next exercise
  • ${bold}skip${reset} to skip next exercise and setup the one after it
  • ${bold}lesson${reset} to see the lessons for the current exercise
  \n"
}

if [[ -z $1 ]]; then
  USAGE
else  
  case "$1" in
    next|skip|fix|1|2|3|4|5|6|7|8|9|10)
      if [[ $UID == 0 ]]; then
        break_fix "$@"
      else
        echo "Sorry, but you're going to have to run this as root"
        exit 1
      fi
  ;;
    lesson)
      if [[ -n $2 ]] && ! egrep -qs '^([1-9]|1[0]|all)$' <<<"$2"; then
        USAGE
      else
        break_fix "$@"
      fi
  ;;
    *)
      USAGE
  esac
fi
