#!/bin/bash
# bb v0.5 last mod 2014/03/19
# Latest version at <http://bit.ly/breakboot>
# Copyright 2012,2013,2014 Ryan Sawhill Aroha <rsaw@redhat.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#
# In fact, this program's sole purpose is to cause boot problems on a RHEL 6
# system, in order to give you practice at fixing such problems.
# Use at your own risk and preferably on a virtual machine.
#-------------------------------------------------------------------------------

# Colors
reset='\033[0;0m'
bold='\033[1;1m'
red='\033[1;31m'

# Location of breakboot configs
cfgfile=/root/.breakboot
fixfile=/root/.breakboot_fix

for i in /etc/sysconfig/{authconfig,network,sshd}; do . $i 2>/dev/null; done
RR=$(awk {print\$2\$4\$3\$1} /etc/[rza]*[-mpq]re*)
L=$(lsb_release -sr)
p=$(cat /tmp/.bbpass 2>/dev/null)
[[ -z $p ]] && p="${L:0:1}$RR$USENIS$NETWORKING$AUTOCREATE_SERVER_KEYS"
functions=$(mktemp -p /dev/shm) && trap "rm $functions 2>/dev/null" EXIT
openssl aes-128-cbc -md sha256 -k "$p" -a -d <<\EOF | zcat >$functions
U2FsdGVkX18uNbSRKBmtyBzFurD6hA2RdasLkTHz7w3yVJpqZWb8L+mlZCosQATb
c9V5J7+frTNyDFrvIrC8CScJzdnjDALGKaMMKkImTKBqL9U75VUW5RuKWptgziPk
T5egmNPyN6d3LJVGh4MNpp/hTlxQgh5erf5qD2qBgM79UCCQEaMwro33p+twX8kY
CalpZzvGSmW9ZCZjpEj7UgNFxnANFH9afx+yJZ938gE/kR2Hbp/ZnumRSN5P2R6T
laPKMA3oriCufFbr/wwvBgyd8ZpcpkC3me54cEbixOjiGGwn1bOs0bz9MQW+U9xj
6Li8kBJ/D4PKBPQlicLfi4mKgxsREHHq0VSom0YK21OvAapPLotPdjfkhsvOLtEx
j5+nzgZcyBwI+wqHK3idwB7cpUTEHDEVT9OPAIMmIUXeH6uQJ2ocIqPLrzrfDexI
DjZXqv5g3VbUkwh72r8rk1NF9kLwyLz6UrXHfnlQ9dLdV6fFoVrJgvWRjZ009/Gg
/EmhU8Dh/DNACy1wOCAtuu/fYR+41XCPiCiJZE33ScCph2RoDM/eelwHJFm8czbg
uhTruRh4+dED1EryzKsgVbr45+0CRKhlqrqSoV1q1opIUORxQhI7Yrjgu8ARv8lB
MCyuj1zp2O6+cch/s71M0MK/50EHE6mn5+qvmf0Qn8i+GGSMpbXMXIBLVzLcnVGx
rCEH8h5Y7oOZI7CN/pVQ7MWoKNMuElbh4mraMILTYSfCguczlJ75DJJs6ZkTxyw7
GettfH/wIJyvfTBX5SDvERhJWVzcD4WaEEIi9qmoDD1Lc0QSO/oDyKE/l69596lW
pqS8FDBgDa+1SEveem5mpnvm85mmlBlSgw/Iy0QnxiRLMYzrNIixeNFYuE+OawTo
fPIj8Esk8OjeAkGGm82FCQ8KrguzPE4+xiGDqYR7Vu2tWrXX2r7WhldSEME5Xh4Z
l0S8qmrJ2oyY6aDJVzuNkqN7jUbGhupvmmnp6vhVIZFfEtHXAzhCwiJRMp9i1Z9r
A7IxTngqMW85zTjGeUnIH+m1vbjqfaH4mUd2bumqlKjtg9gTn80elRhIcBkrG+fk
2Cw3x45UkL88JYcd0zpX3m5q4GRPkfCpd+NfOO4UGDIDUX1VxZHqWjPrqXPTYpyG
Jdm53hiGP10xgIzun4AlZVz49btsdhaQ8kt75/1gaw+V9UsIY9ka3GUWI8Pn+usw
G/1ezlHVW+WkaqiI2Ov2vFut022P4SsKFvfn66i27zAp7latOqaScYcT3zagMBRK
Ouq4F7Woz8pD0lnLfuzNhXc6WFt41fVFT3I6PwCcS5K0jQEVdlfSU+ChQkvP3ecc
xQFX8UL/nE5JbirGyNbJLyJyhBAirsEKjnnjW3kiH2E9twpknFVK7ZaIAHWAEt3M
vrxpp00S5WJ2XCaTvU3DkMTGCe2EwWeiJ6ADQqiyPVQMA6DvvzohK2ZffSfN2A8/
mT0ejcmIMpdY2ArGm4gKfNzDkv4O+r9mEcei520z6WCQb3v251zbl2aZlff35VTo
ZRktQQxAq/CUsn2Edx5DiS5DGAaBrZ4RQ7hiB/W4H/SSshatDt4v14lpgd20wZjY
4JW0G7oMx5vzLbi3V/9Z6DzQHdGFwKEGVtMs5wBoLJTrWol7WiHcBUXlA8q1qaqg
Oe107VSxh4ddqGsKRCMSNWFaEWVkkThPdsuUksNczEgRP62pnNLTIvhm9ezIfwDP
THhu4FG3kCmiexYLos3IqafaPMmTw/+CmlrSTVvp84ebFlMwjp2sMfQaIFueD+Ig
0L26liCe6l/Tc1Tz9umyECXQFg1jFbX0NQ9ql9Jcgk/5b4UOw+I89Q3C2Ygb6tNU
vbrC5j0bFqs0Mrg8Z3POvvTvbWINknN2+C3UvcSZ8N6wot70+wTjHN26+CGHZWlX
t0BlhtT/c3KmXcWMFzneYp72jHVEnxRg+SPNaj+mLrTZ8K1d7Sy6s8Imveo0C7vT
8Oaz4M3QCTYBvyiCOJL1XKa9IGjhnHilfvW3mjSKfueWFJBA0NBG25iCImiywvR2
XmZTjs7B10e9NShBMXzcoUrRdphuuW4bW4IIqNiihdOJSkD4c9NM1Q08mi+cT2CG
U02S0KZxEXdxHpNw94kEjBbwyQ/QVutYawjHz4cJOeQ+eO4ZHFIoUG3wzYLbUdIE
HUQUOeToEWDY1EF3CbOeoTqKO7sdZGgMZeLo2XbdHDm0c2/d4Ns8lRU3oSuBFlrh
M5PV9V3kjh/OuuIYzLEyITkibUvoQ/1O8W58l0x1Gmr3O/cGYqn2t/M1WkA9Torl
8lXSl+5E9iikKslyeGP7zPCZxdPYho6y+RZEfg6VWrg9GK2CMMsvqm3lVvmyKXRh
CRKccweciSTB8HqCczta5+nyK/m4X46v4YIqr6Arza2+hExFhBg6k8CGweN/HQ4t
jHPSwFjR+gsM87L+YTuPM6RjJeJEddKlBDseE6rZnqdaF7ttNM0RXiL+mmb03Juh
TXJGYTPJoWkxwhMxmaciDMsRaOLmLRHZt1XSjJQxDGLXkbCM7844ZLGGdoLajIBF
x3BQgFKRVJfsYAy0z2T5miRxGFZqOIeNjX4n7rdTaY082tNcdzGESrkOMUfTXQoo
sBN/GdLD7nSbcLKzFNw4kzM/sBbGYrjK07JJjaHsqW9riTcjwJuwDnrBr+qoBwZr
8aB3L8t5qsvwa9/vHR5e3biyTc6N3fxh0TXxyKjTT4gUOcB4BIvZj5QoBe+ocQ3r
n4OQcwl7L18NHnjrBNR9VLT4oozi44BUVxCioinpnC9GuSfGiadT0IksnoO5cxLi
bnCjXxiGq5VdYs2rakQbExVau2WMo0jUnWvoF6rlrlDfkUWVEWQ1e2XT7jSqeL7e
HIkPfqvV4FjuMwERwMwioam1nurWdCA2w6Tx/DsUmC7vEg9g/g0u4+FnH3s27Yz1
X8Z9Apx6/qAJeWZjXu7A96iDCsIwNpXz/ET99AI1Bd3q9ungXrTtJ+BbmXAPo+SP
SoFK65ah0kCKbSdzHCLqV3mlq3JzyTR7QIQDzmZTuTgljrEbaQ0Wpq5bhcqmXY7T
U5vy0H8CdV0wmWCtkShxWj33KDPXuKQtIr3Ovxj/7QONepurwTJc1cLZABYN67R3
SaOFMl12YqjAexAf7Wm2yCoMhs0PTwzUuo/z8Ik+s8MRzOMZ9d4pIV543/BdVnKw
dCF9AlPUSgm51hm3k3OhAGJmz7WX+A4KfqbVHvNn7Q+0qZkWDwN/8UnMY5Qqg0bQ
ESveHkLPBeeeriDN+LCJ60XHvOlXM/PxtSICVtTBW8hSplJ6OZ1BJJbs+BN/zw0O
/H3vi8bdoa/kcmrgb8Hlc/MPzLJLwAFrJsivTLkXuobXT4gBe+uMjAojbbKhLZLF
8b4yZNnGi4fdl4khMGvQK5ufJm2Z0rpc4bzmE+U6dEWEi50KIpvSBRf01b/lY/6O
jCNdZhyPuyJ9UyxBeeqHVHwse4rp2VavU4L5IUufmJdzufFz2dWTNzzkqf8xItj8
KRO8TK0p+3abCCSV7uLjaVhC7QrqAZnHoeM+OqyoNBt35H/VELPWt9m36jN6GVQw
vsBA46oNDls46oVaVFniOzHeihxiMeWY/JnaDrROpBzsAWdthl2XjfGjJnPpLbwt
vSL5Q+sitRVihUgUV1Zu0Wggp+kQRMBOnBK6ZUMXfWydp4P19gInhWgNoYvbOR4W
Gxiegns7cw4+U8qE/uXnGLAUDx6+gheZAjzfvn8c0Oltwoj6sgqtzJmii3CAHC7L
BV4KxBvwK/smmL4DVx6iXgTZCWH3M3IhPJVI9so8Svadost+Uhkl3jhhRFlW1+zc
APSZz0eFpOil7cdGG00a1o2o75icPKOeedQdp3gKd4zl68gSuE71BLa+VyveYUlg
i7teqWnkB30wpP/w3/v/7tVT7oq5UncC2Wg40g7/I+41FzS02IJHGUOebzruOK59
/zoaSqw//SobzysKkGyBLQdJNeHtYRAX+l7/u//d6DyYOJULqOELLXfZtJ+x0Ihm
XGUHeiLFuiyw9obK0X/2ihx7Zq9kOjcIO9SC+48GYR0R19NOzgWhqOHwaSgCkr4A
NR03h2NXlTxFn1ilBw4trW2kwX1IXC+umMxq8/pKmq8Q+0Cc9FhpAKuj7fbnmENR
EjPSDWIq/8PLYzVsnhiGH43YA4Luyqpe6uFIyVk2uxdNO3hOabaC8CsXcNpoAyz8
bIVfxnXypT4+vm5xI+esL7vnjsbx06r2sG+UdtFa4VCIlZIprxAVzriw4dODVdb3
eyiQ5W0UEHi81Yf/rL1IWfNVBIAB6ndYGmduXFGmthxjDMHGb/q4YXJMbyGcVqBg
epAZJE2JTfoBFaLFM5ZsPtA0UU8eRkym9O8ZtxZstqo7R8aDw4BSfe1Sjbmpogw5
aHRRHWUgIOGVwGUyv02tcucsUt2qyMyeHcl2xyXpWOG5JkdB6emSreTylQzTt9tO
3CLJmEIaTLOMFHXPnYoi5W29ZgOaGa+S5xPOUpX26yTysrOhfQvFxPCunKBj9xVU
yYmqeckWSG+GFMnUtP43SZdG0uAR2caCqlRlRnfhx1s9+hSHm0hzc+HxQUUZZc9z
s4JvtFTyCpxnXT8njmYiyJQ7Gu1lWF++A/63TWY0fpS/PnIKFpYvBo4gGX3cfkti
LAFhGpRC7RfTIcdyIsG5WTLmhmg8MsfLEQ+XXj9evS4F0I4H7stHEN8obToUssbF
++bRwDxZxUiXrXz8SV/zcuHKeifHWEL+heACtN0jQd75dzkJJSF/Tc0HM7Ry/4ZW
Oi9Je0mhlZ4JPXTDJvhtMtNBdHaO5oAT86EIcEhSl+fahg+I6nbYMMdXszxANgu3
roYxfBkpkclvWeGOLo7hYykfx8JVEN5EapD8AOjMVxct2l2INLp4J+VWgSXrE2CJ
MudkrQ+UyV+HLBWpUeif0LcoIkybkDREgJXtfEaQfSi3gyjpsgtf8X+NED5VWZMq
q2sR2lFkfe3asigSxTIEv+haVzUExS/+tDYwUgKwlmiwnJa6h/vzE2BePRKlRELe
3hEBK07w/DKqkL4psVuVX62V6YvVwsK+7alNNqc6XkcKCs+p9VZ2qVSu6DzZfrAd
xddgNK5GENjQx3/Ok0Bao047G1K8RrlPoNGF/jOWPiSRPDg4wTXXGps4uZO/4zAp
NxcP79aU0Qmf+uHZz7/nIHj8Rmwu0fwJZjnpYjzNwVHWMa0VVNznynv8v018IDW2
g6wrq8xxALij6M954NZndjar+JqScWUluetjqmeHgv8i4cTaEaImi1m168TQg6Mo
O4I7LOlCicq4p5mCoxVdaBvokEz0Vabu1fSGS4vxHralptar3hockTTjBRUXCtuS
NvJOzKnuiS/B/zS9xkqThuIKlRwpGbVZHejBr/3HWOeSeTDuWDvv+ftAnXLdNJHW
oGH6UjAoyhPZCPcPU72NmF39AVnYkKBLucAn0QP2U1l+0dr0SrY/1b4aSWSeZ0nv
SF8V/fth7Q3d7srRcQCXGsXHIXrRE/GPgG6QG83UxnCoQLPpysf0rKJ1cH4/I88k
rcLb6UBKuhnc64sPsc3n6NLhuMsgr/MFLVW43744H7Gh64EdxKJlwuq/30Fhls8C
M1ub5f1miigrMRiexz1H5CDiIyFVydIf1HcZqZGFJXJAz1Rldo3gkwOVq39OJgSD
8/83R3NFS96KQ/DePLH+I4lHVM0KI1ND5QyfgAIZtkTSYV5wj36qtnkWk7uM8fV5
ptdYOSpDAvicTkcIJbzEWjjhXRdPXWIpu2B4UJfu5YIYETONvW1DjfQuBoUfsMJ/
0Wjyh7ozMpKNyhPhSOfz03eX9sgOfnOs/YIOhpIcwlU7bQ2MdIwrwrBvViMssrl6
e71ngH/gxpRNkOez07w+QeRKnU1Do8DLvU8fBMjrgRrRLUkDZf7PLAmwPMwKk62P
wBlPwp2vKst4LGkabruU3XefjE6JzbvRFGFsEZM6W7In/53tp+vlrVOS8ybUNAcp
T/MuOzBVKn7Al3nON5Cp0eihDW4a01QWc2DYO1dIlVoR6TcrA4Br92CwQ9DYB0N2
IbITI+a3ofoC8PD9LT4v5p91k8Px1F/TGZFoOSf3RNtxeIpCwu+/CNlo/d/H1qCv
mYu5AYfz0sVub9GynFIqGLA1DbB8NKt9QAga2RzUl3AHUMwljasjicwNJcRvbqNx
ioakKt/D0DXjY4StxJe1iRydyW1WPI65dAqhS06NYHjpCP6aTRHlRYfvpipVxNO3
8XPg7Aq2t4kAIUdVGSWcmMsU3cJTXO222rDZnF0r59gXesIjQgIuyN3KsPTzKjJ+
re3oOey1vK/Z7+6G5zzv04Zw6KljcsqblGECM/Ei9+90zY0lirh5uhXhaXxUXwJ0
ftGDH4qMXcozuZ3pX/taW9tsiKSuNd6PxiNWhCfgdGTQOJFtS2W2yvgokPcw53d9
hqdPFPq0qjkQlFq2cGJ5ePvBp/fx/V0d8UI6cBrFFsoqxciAEoJoYHyPIvGLgmD7
5W+C/hUl2O+2JXvE1kJM5QX3L+JAKTyM94QeyMdq1au5JZ/9UaPiaHH/I/5Qpdlw
0Vt7QsMa64FqQKHXBDhc0axw9sZBxbT3o09p2+fpg5kVNH5dRTwu+/bSvr05AqnK
haOhKrdQ5dumMu4mez9/mLiXsPUfOZnOQWQ7hUfJJjr/DzAhbrQ7iwoUdYEjC+nf
RZePmRFr1njJbon+VWqQV61c3ogR6eJRt06OJ4JseayzCbHBtUt2Kw20USdIzl+l
+lfbDb2q7OsWVWLlnjw+Pj+V5ZcrZ3qQJjIWdd/OOCNkPolt1SrWUeK1dKVPoXdt
jq3sMGjYs1EAEyzh1Sq0NIXF2VaS1AZHjWUC6RiMOfAeltah3WP6dtKlcUOzz3/G
tD4hjmYObOaj3LR3KqJvO+7VW6yOqwQgNjfIgZx58oiBZ/O0tFO0lBIYcV0h4o9S
ecuZIVqnBJNmnIJFEnkVNpDUDm+0WE+BHu/TI3k6ywKiC4eoMo3p0v69Uh1oBIH/
bV1t9/O835q2YBYjFIpEP8NN8IIhcg+bjAbrlfFmDHnwbYzo6cSVO8txZz4dyaUa
mm8PmioOGz+AwphL4VHzavsQ1coZcBIrNz5ilUFVcHuDqJVg2nFzYUJopnYLiKEq
dX8QLgpJ6N/iM4mBf83lAo0VfyTXINa/wG41Av+mXKeeT8AkHa51/5CYQ/USdp38
W+Y29FTLwHhGjS8HSoT4ACEknbh9/Kc96ka+qTbubF7Ttrmi3UP+8pJ7skterb33
psONGJWQcddmgPewVwNIli0jDAMC0ugLhdWe6G7lcFpP0wIq/dx00HVLWJ4/glx3
86E30kotbe+z72Hk+GbasjMwFU6D5dIj/IoXPvp0JGAefsd2Ml+zzPv/OOF1UqfU
TujuW5nTNcSvG5t/I8y8REtiLg2Okw6sjeOaZTC1GANU/15uetZ19L2G6AMlIqRT
Jfkm0GpKHEqRA/Q5bGaz/9tpCM4a7nzLewx0wVixLBH7lMYd7B2iUv7JUvtT8WjP
5DDwiIbANxgPhrK7rMQTJYdxPmUx5vEKK4yDrp17SrTP80BJINZYp24jiAPAmRjj
vnIVd5pdYdlF4UpxoqQwsEeQ3DanCzbTRsL4F2VxyoRHfs1cboxc4D0e1u3V3l9x
DGJscKsqbS+sEiAPIbv9/QWkEa5qjlcsKl5GnbRoXviqvR3NT6wIH/gbsyiUatk4
GiC1R2tFjkZzc797pGJuwS34Bcto5P98lOyHE91jkkCa+emjckEcSdi0vY+rKI+b
8s+N6VOe89KDPz3dC0mw+bxgR1tNSB7z+1AG1h6ewbQxLZKCQzK77QhXcbHOAgb5
X8evymKzkGyidmjriltpKCZsErFTNjzHpglW3jdCJJ08E3lwmK9+rvUY4YsQJz9L
j069yLTCQSoF5T+6Pj9/GBRHpynEDDdS8pen8CcEuSMBasdzKZklifE3WEhq/BR7
4rYSH2rhPKpmRVa+f1J853m70q4A7WtXqDQddMKSoa7zmJTT7Fn+v50vTnW4ZDWx
G1IADW4yxKhDfSyo3aAk4HH4GGdYlF6mEWhfr8ZiqLYZBj2Qf9HPv4JSweEB8JYk
4HYnB3zuLW/N2YJzBjr4lV4clDRyW5Lec0CKEQJs9Fwk6vyu33Kh57YCeMR9FbVd
o8YJ+JiT1JXVj3CKWOQHMUvdKT6YjDTV56KKpwsPpqOem/hVhrhoATlT0kLj8oLE
GMtKQ5Nhe4TtOWh7ehqQ0jq3qqne2u578mSUgSE/vgJWnbPZqbjQEpsVJEF2jx69
VXatXP7K2SeRoocZaQAPf7rzYiOVSacRxwF74yRo+oYbPFzvn+LaKyFpYLCoFglF
KXcZbaepA/VlOXC22NYKvz9qmUT7tbdCKgi/qExA1FgoIKqPwYGSuNx+je5DRNgU
GMIsFwM7BXYMR+omNsnIEs+tB7gE9ZQ5kTdGJnyIY6EZ30RZYpVF02OSdSiF6gc4
Jq7ZSLd1kwwSFkHF6BGHbRw5v7gPJg5yxDxpU/oPniWaYphG83KlLMqN/AB7W0Zr
QZ84Y9cM4Lxdqv24IW7T0vAnFSzwm+odzyptxgwBSqNPZSTgXjW7ohMviVShHSiY
nR2vyvRHPrgu8LV488NpBvYPQ3r59ofrJr3UzlPDHcqRGnA29AJvs3Ir4V3+n1Jf
1pi0ANImN7zXlonE/fQMnhJz1krqf8WFywMQcpcdZb8FfGqA2L9hYbVky8n/+Sf3
F3XLe/zqoBb0q3y4GRQNyAqsMbktM1Li33xZUeEo79/KgBWp3tAD0l2ahot9V+2+
v4fKPSPyRLKCk8soO80XtJbUAFfUxkCpy89j9XUGRQJfcMF6MDlqPnUVK1rgK9n9
fp5gLkAcwXdQXoAWc6cDhzQkgBk46Mv2ev/mysZK1TGXRy/Gc7ZTgSGrI/KLJaXK
+KfS4pRh3mPgqwKBXUCXDSfH8Xfu9L7KlcUJ1peloxnxFjI6IL7XMtGI/g0N1JGV
sK5HLamqq8Lq/j4D+zlXA9ONUbnLX8lbQuhxu8Z+RTGTGNgrMmVytVnSxCrR0amy
Be+fSGV+J0EuqPRapggixMm8Ok+POO2jyB+d3sp/OO+a9YS1v2TQuOqNPZnOWU4w
hRzdFWOicXWo70O4dRhYfHU31jjq5wLudY0jrD9RSUX4FUjiFyP6gZUMrBQW2I1S
1Hb+/fXfaOylh1+Vbx0tgEsYGknh4jYWWuo+HozeboMfcZILkLxH0cW8H5AKiYc+
BvmrMruCIn5BTLyB4kRTD68iyhr5OMst5C39jy/kzq5XJVxgCBs24OVsRqRguiQg
9ESpMdorc5BB//FlbJBDs7448YBg5btkcKqMC8wz6sRn+7IJmrWEuHrgmbiJVY7O
ulr7DY3XDWBStvkVGGa8iBQZA2Vj29iD75THQuP1DLodLeH61GQyiu17CzAuEvWp
yfeYBGs6xjIHkh88MppsB1GBedNx6B37wf7ZaN0XMixpLA/ap4fMpCMPRzXuOqDg
YS8bctU6umsRWoUPCPXifO3Cji9GRc9scC5WK+SXUu2kVtSEbPUWd/++GrVSpLDL
L/ebqG+mn/D9wOsZ0ykGX/ste3rvR5COzHKD0wVTxHXjT3HofO5BVa0KM/YMgMO8
p9/uA19aJVwAyGfx3I0fQbO8yihLotNp9zth65M4WVdFmLjZNW59Qaf2NnjYLt++
EgQmRnVOFH03HGuFlts8dehiKRgqhbNtDQM315lM8E3xVV9OnleC4ISUhpGO2PLF
b3TUqzTE44R5B/BF6p1jsJuMGFanpLcKlD60FoD2/0BGKJ4L4EtmBMDLYz+MiwLm
Yj6xXnmaD+l4fNjRVT4aznhA5fNA7uO67SezLHrkPbK7ZzvEjUzkAucxi7hioyvZ
kijBpFaorTD0VsEsr95qE5XZtE7hiICLgQHwxGXmWFnPdbQq9cs7DHP2xCiq92Os
4dPhDRnzsfHKz32MzbN8BpR4vK5jDjgjDgcFX/q2QJYxG1PKVFBwuzbKtRs3Wj/q
2ReJsA33HF3FNQ5PDeevrnTWGy6Yj7wob9QFmvorH0uUQn3XW9NJ1IyWj5n0vL1h
JuRjWdLPuH7KdRannPxbE9gcme7FMP0IOyez0pzho9QCkFSPvROVvwMxmCp10W1z
w3DtRpx2fyfEOXMreLJRcH87dpEgNN3pSMUPTKZf4SkslzUBjVTt/9MXEMlaUVw+
EOF

. $functions

USAGE() {
  printf "${bold}Usage: ${0##*/} { 1-10 | next | skip | lesson [1-10|all] | fix }${reset}
  • ${bold}1${reset} thru ${bold}10${reset} to setup a specific exercise
  • ${bold}next${reset} to setup the next exercise
  • ${bold}skip${reset} to skip next exercise and setup the one after it
  • ${bold}lesson${reset} to see the lessons for the current exercise
  \n"
}

if [[ -z $1 ]]; then
  USAGE
else  
  case "$1" in
    next|skip|fix|1|2|3|4|5|6|7|8|9|10)
      if [[ $UID == 0 ]]; then
        break_fix "$@"
      else
        echo "Sorry, but you're going to have to run this as root"
        exit 1
      fi
  ;;
    lesson)
      if [[ -n $2 ]] && ! egrep -qs '^([1-9]|1[0]|all)$' <<<"$2"; then
        USAGE
      else
        break_fix "$@"
      fi
  ;;
    *)
      USAGE
  esac
fi
